### ISSUE TITLE
Potential runtime panic detected by static analysis

### ISSUE THREAD

**Issue by lizhuohua** [aesedepece/scriptful#1]
The following code would call unwrap on None:
```rust
use scriptful::op_systems::pokemon::{pokemon_op_sys, Command::*};
use scriptful::prelude::*;

fn main() {
    let mut machine = Machine::new(&pokemon_op_sys);
    machine.operate(&Item::Operator(Evolute));
}
```

**Comment by aesedepece** [comment]
@lizhuohua thanks for noticing! May I ask you what did bring you to scriptful?

This limitation is indeed explicitly stated in the documentation of `scriptful::core::Stack::pop` and `scriptful::core::Machine::operate`:

https://github.com/aesedepece/scriptful/blob/37f6ff8361077ac63ab861273ba75b4f0571706d/src/core/stack.rs#L62-L63

https://github.com/aesedepece/scriptful/blob/37f6ff8361077ac63ab861273ba75b4f0571706d/src/core/machine.rs#L58-L61

I'm planning for a new version that removes the [smallvec](https://crates.io/crates/smallvec) dependency, so probably it will be a great opportunity to handle this in a nicer way.

**Comment by lizhuohua** [comment]
Thanks, the docs are helpful!

I am actually developing a static analyzer for Rust as my research project. I collected some most-downloaded crates on crates.io so I could test my tool. That is why I tried scriptful.
